name = "portfolio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[pages_build_output_dir]]
# This will be set to your SvelteKit build output directory
value = ".svelte-kit/cloudflare" 